"""phase3_army_builder

Revision ID: cfc559129f0e
Revises: 38fbd9806a21
Create Date: 2026-05-18 19:35:06.528774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc559129f0e'
down_revision = '38fbd9806a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('edition', sa.String(length=32), nullable=False),
    sa.Column('ruleset_label', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('factions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_system_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('grand_alliance', sa.String(length=16), nullable=True),
    sa.Column('blurb', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_system_id'], ['game_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('factions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factions_game_system_id'), ['game_system_id'], unique=False)

    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('requester_id != addressee_id', name='ck_friendship_self'),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendship_pair')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_addressee_id'), ['addressee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_requester_id'), ['requester_id'], unique=False)

    op.create_table('armies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('battlepack', sa.String(length=16), nullable=False),
    sa.Column('points_limit', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('public_token', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('armies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_armies_faction_id'), ['faction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_armies_public_token'), ['public_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_armies_user_id'), ['user_id'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('base_size_mm', sa.String(length=16), nullable=True),
    sa.Column('model_count', sa.Integer(), nullable=False),
    sa.Column('unit_role', sa.String(length=32), nullable=True),
    sa.Column('can_be_general', sa.Boolean(), nullable=True),
    sa.Column('can_be_reinforced', sa.Boolean(), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=False),
    sa.Column('weapons_json', sa.JSON(), nullable=False),
    sa.Column('abilities_json', sa.JSON(), nullable=False),
    sa.Column('keywords_json', sa.JSON(), nullable=False),
    sa.Column('companions_json', sa.JSON(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('image_source_url', sa.String(length=512), nullable=True),
    sa.Column('image_search_url', sa.String(length=512), nullable=True),
    sa.Column('wahapedia_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_faction_id'), ['faction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_slug'), ['slug'], unique=True)

    op.create_table('regiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('army_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['army_id'], ['armies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regiments_army_id'), ['army_id'], unique=False)

    op.create_table('army_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('army_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('regiment_id', sa.Integer(), nullable=True),
    sa.Column('is_reinforced', sa.Boolean(), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('is_general', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['army_id'], ['armies.id'], ),
    sa.ForeignKeyConstraint(['regiment_id'], ['regiments.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('army_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_army_units_army_id'), ['army_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_army_units_regiment_id'), ['regiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_army_units_unit_id'), ['unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('army_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_army_units_unit_id'))
        batch_op.drop_index(batch_op.f('ix_army_units_regiment_id'))
        batch_op.drop_index(batch_op.f('ix_army_units_army_id'))

    op.drop_table('army_units')
    with op.batch_alter_table('regiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regiments_army_id'))

    op.drop_table('regiments')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_slug'))
        batch_op.drop_index(batch_op.f('ix_units_faction_id'))

    op.drop_table('units')
    with op.batch_alter_table('armies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_armies_user_id'))
        batch_op.drop_index(batch_op.f('ix_armies_public_token'))
        batch_op.drop_index(batch_op.f('ix_armies_faction_id'))

    op.drop_table('armies')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_requester_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_addressee_id'))

    op.drop_table('friendships')
    with op.batch_alter_table('factions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factions_game_system_id'))

    op.drop_table('factions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('game_systems')
    # ### end Alembic commands ###
