"""phase2 game systems factions units

Revision ID: f58946f636be
Revises: 705c15c80e95
Create Date: 2026-05-18 18:03:15.841067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58946f636be'
down_revision = '705c15c80e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('edition', sa.String(length=32), nullable=False),
    sa.Column('ruleset_label', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('factions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_system_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('grand_alliance', sa.String(length=16), nullable=True),
    sa.Column('blurb', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_system_id'], ['game_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('factions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factions_game_system_id'), ['game_system_id'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('base_size_mm', sa.String(length=16), nullable=True),
    sa.Column('model_count', sa.Integer(), nullable=False),
    sa.Column('unit_role', sa.String(length=32), nullable=True),
    sa.Column('can_be_general', sa.Boolean(), nullable=True),
    sa.Column('can_be_reinforced', sa.Boolean(), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=False),
    sa.Column('weapons_json', sa.JSON(), nullable=False),
    sa.Column('abilities_json', sa.JSON(), nullable=False),
    sa.Column('keywords_json', sa.JSON(), nullable=False),
    sa.Column('companions_json', sa.JSON(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('image_source_url', sa.String(length=512), nullable=True),
    sa.Column('wahapedia_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_faction_id'), ['faction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_slug'))
        batch_op.drop_index(batch_op.f('ix_units_faction_id'))

    op.drop_table('units')
    with op.batch_alter_table('factions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factions_game_system_id'))

    op.drop_table('factions')
    op.drop_table('game_systems')
    # ### end Alembic commands ###
