"""wave4b battlepacks templates match_battlepack

Revision ID: f9803530f860
Revises: a5ee9f35ea88
Create Date: 2026-05-18 21:23:15.339636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9803530f860'
down_revision = 'a5ee9f35ea88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('edition', sa.String(length=32), nullable=False),
    sa.Column('ruleset_label', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('battlepacks_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('primary_objective', sa.Text(), nullable=True),
    sa.Column('secondary_objectives_json', sa.JSON(), nullable=False),
    sa.Column('deployment_text', sa.Text(), nullable=True),
    sa.Column('special_rules_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['game_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('battlepacks_db', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_battlepacks_db_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_battlepacks_db_system_id'), ['system_id'], unique=False)

    op.create_table('factions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_system_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('grand_alliance', sa.String(length=16), nullable=True),
    sa.Column('blurb', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_system_id'], ['game_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('factions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_factions_game_system_id'), ['game_system_id'], unique=False)

    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('requester_id != addressee_id', name='ck_friendship_self'),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendship_pair')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_addressee_id'), ['addressee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_requester_id'), ['requester_id'], unique=False)

    op.create_table('armies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('battlepack', sa.String(length=16), nullable=False),
    sa.Column('points_limit', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('public_token', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('armies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_armies_faction_id'), ['faction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_armies_public_token'), ['public_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_armies_user_id'), ['user_id'], unique=False)

    op.create_table('army_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('points_target', sa.Integer(), nullable=False),
    sa.Column('units_json', sa.JSON(), nullable=False),
    sa.Column('regiments_layout_json', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['game_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('army_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_army_templates_faction_id'), ['faction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_army_templates_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_army_templates_system_id'), ['system_id'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('base_size_mm', sa.String(length=16), nullable=True),
    sa.Column('model_count', sa.Integer(), nullable=False),
    sa.Column('unit_role', sa.String(length=32), nullable=True),
    sa.Column('can_be_general', sa.Boolean(), nullable=True),
    sa.Column('can_be_reinforced', sa.Boolean(), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=False),
    sa.Column('weapons_json', sa.JSON(), nullable=False),
    sa.Column('abilities_json', sa.JSON(), nullable=False),
    sa.Column('keywords_json', sa.JSON(), nullable=False),
    sa.Column('companions_json', sa.JSON(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('image_source_url', sa.String(length=512), nullable=True),
    sa.Column('image_search_url', sa.String(length=512), nullable=True),
    sa.Column('wahapedia_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_faction_id'), ['faction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_slug'), ['slug'], unique=True)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('points_limit', sa.Integer(), nullable=False),
    sa.Column('army_host_id', sa.Integer(), nullable=True),
    sa.Column('army_opponent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('current_phase', sa.String(length=16), nullable=False),
    sa.Column('active_player_id', sa.Integer(), nullable=True),
    sa.Column('scores_json', sa.Text(), nullable=True),
    sa.Column('public_token', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('battlepack_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['active_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['army_host_id'], ['armies.id'], ),
    sa.ForeignKeyConstraint(['army_opponent_id'], ['armies.id'], ),
    sa.ForeignKeyConstraint(['battlepack_id'], ['battlepacks_db.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opponent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['game_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_opponent_id'), ['opponent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_public_token'), ['public_token'], unique=True)

    op.create_table('regiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('army_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['army_id'], ['armies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regiments_army_id'), ['army_id'], unique=False)

    op.create_table('army_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('army_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('regiment_id', sa.Integer(), nullable=True),
    sa.Column('is_reinforced', sa.Boolean(), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('is_general', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['army_id'], ['armies.id'], ),
    sa.ForeignKeyConstraint(['regiment_id'], ['regiments.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('army_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_army_units_army_id'), ['army_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_army_units_regiment_id'), ['regiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_army_units_unit_id'), ['unit_id'], unique=False)

    op.create_table('match_dice_rolls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=True),
    sa.Column('formula', sa.String(length=32), nullable=False),
    sa.Column('results_json', sa.Text(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_dice_rolls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_dice_rolls_match_id'), ['match_id'], unique=False)

    op.create_table('match_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_events_match_id'), ['match_id'], unique=False)

    op.create_table('match_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_messages_match_id'), ['match_id'], unique=False)

    op.create_table('match_casualties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('army_unit_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['army_unit_id'], ['army_units.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'army_unit_id', name='uq_casualty_match_unit')
    )
    with op.batch_alter_table('match_casualties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_casualties_army_unit_id'), ['army_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_casualties_match_id'), ['match_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_casualties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_casualties_match_id'))
        batch_op.drop_index(batch_op.f('ix_match_casualties_army_unit_id'))

    op.drop_table('match_casualties')
    with op.batch_alter_table('match_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_messages_match_id'))

    op.drop_table('match_messages')
    with op.batch_alter_table('match_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_events_match_id'))

    op.drop_table('match_events')
    with op.batch_alter_table('match_dice_rolls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_dice_rolls_match_id'))

    op.drop_table('match_dice_rolls')
    with op.batch_alter_table('army_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_army_units_unit_id'))
        batch_op.drop_index(batch_op.f('ix_army_units_regiment_id'))
        batch_op.drop_index(batch_op.f('ix_army_units_army_id'))

    op.drop_table('army_units')
    with op.batch_alter_table('regiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regiments_army_id'))

    op.drop_table('regiments')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_public_token'))
        batch_op.drop_index(batch_op.f('ix_matches_opponent_id'))
        batch_op.drop_index(batch_op.f('ix_matches_host_id'))

    op.drop_table('matches')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_slug'))
        batch_op.drop_index(batch_op.f('ix_units_faction_id'))

    op.drop_table('units')
    with op.batch_alter_table('army_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_army_templates_system_id'))
        batch_op.drop_index(batch_op.f('ix_army_templates_slug'))
        batch_op.drop_index(batch_op.f('ix_army_templates_faction_id'))

    op.drop_table('army_templates')
    with op.batch_alter_table('armies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_armies_user_id'))
        batch_op.drop_index(batch_op.f('ix_armies_public_token'))
        batch_op.drop_index(batch_op.f('ix_armies_faction_id'))

    op.drop_table('armies')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_requester_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_addressee_id'))

    op.drop_table('friendships')
    with op.batch_alter_table('factions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factions_game_system_id'))

    op.drop_table('factions')
    with op.batch_alter_table('battlepacks_db', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_battlepacks_db_system_id'))
        batch_op.drop_index(batch_op.f('ix_battlepacks_db_slug'))

    op.drop_table('battlepacks_db')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('game_systems')
    # ### end Alembic commands ###
