#!/usr/bin/env python3
"""
gen_phase2.py — queries the DB for AoS4 units missing images, generates lex_devtools_phase2.js.

Usage (from project root, with venv active or inside docker):
    python scripts/gen_phase2.py

The script derives full-res URLs from the thumb URLs stored in image_source_url:
    Thumb: .../mediawiki/images/thumb/<a>/<ab>/<file>/<NNNpx>-<file>
    Full:  .../mediawiki/images/<a>/<ab>/<file>
"""
import json
import os
import re
import sys

OUT_JS = os.path.join(os.path.dirname(__file__), "lex_devtools_phase2.js")

# ── DB query ──────────────────────────────────────────────────────────────────
# Allow running both inside Docker (via flask app context) and standalone.
try:
    from app import create_app
    from app.models import Faction, Unit, GameSystem

    app = create_app()
    ctx = app.app_context()
    ctx.push()

    aos = GameSystem.query.filter_by(code="aos4").first()
    if aos is None:
        print("[gen_phase2] ERROR: GameSystem 'aos4' not found in DB.", file=sys.stderr)
        sys.exit(1)

    rows = (
        Unit.query.join(Faction)
        .filter(Faction.game_system_id == aos.id)
        .filter(Unit.image_source_url.isnot(None))
        .filter((Unit.image_path.is_(None)) | (Unit.image_path == ""))
        .all()
    )

    raw = [
        {
            "slug": u.slug,
            "faction_slug": u.faction.slug,
            "url": u.image_source_url,
        }
        for u in rows
    ]
except ImportError:
    # Fallback: read from a local JSON dump if app is not importable
    fallback = os.path.join(os.path.dirname(__file__), "cache", "missing_images.json")
    if not os.path.exists(fallback):
        print(
            f"[gen_phase2] ERROR: cannot import app and no fallback at {fallback}",
            file=sys.stderr,
        )
        sys.exit(1)
    with open(fallback, encoding="utf-8") as f:
        raw = json.load(f)

# ── URL transform: thumb → full ───────────────────────────────────────────────
_THUMB_RE = re.compile(
    r"(.*)/thumb/([^/]+/[^/]+/[^/]+)/\d+px-[^/]+$"
)

def thumb_to_full(url: str) -> str:
    m = _THUMB_RE.match(url)
    if m:
        return f"{m.group(1)}/{m.group(2)}"
    return url  # already full, or unrecognised pattern


triples = [
    {
        "slug": entry["slug"],
        "faction_slug": entry["faction_slug"],
        "full_url": thumb_to_full(entry["url"]),
    }
    for entry in raw
]

print(f"[gen_phase2] {len(triples)} units need images.")
for i, t in enumerate(triples[:3]):
    print(f"  [{i}] {t['faction_slug']}/{t['slug']} -> {t['full_url']}")

# ── Generate JS ───────────────────────────────────────────────────────────────
url_list_js = json.dumps(
    [[t["faction_slug"], t["slug"], t["full_url"]] for t in triples],
    ensure_ascii=True,
    indent=2,
)

js = f"""\
// lex_devtools_phase2.js - auto-generated by gen_phase2.py
// Paste into Firefox DevTools console at:
//   https://ageofsigmar.lexicanum.com/wiki/List_of_units
// Requires an active CF-cleared session.
//
// {len(triples)} images to download (units missing image_path in DB).

(async () => {{
  // URL LIST - each entry: [faction_slug, slug, full_url]
  const URL_LIST = {url_list_js};

  // ── LOAD JSZip FROM CDN ─────────────────────────────────────────────────────
  async function loadJSZip() {{
    if (typeof JSZip !== "undefined") return;
    await new Promise((resolve, reject) => {{
      const s = document.createElement("script");
      s.src = "https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js";
      s.onload  = resolve;
      s.onerror = () => reject(new Error("Failed to load JSZip from CDN"));
      document.head.appendChild(s);
    }});
  }}

  // ── HELPERS ─────────────────────────────────────────────────────────────────
  function extFromUrl(url) {{
    const path = url.split("?")[0];
    const m = path.match(/\\.(jpe?g|png|gif|webp|svg)$/i);
    if (m) return m[1].toLowerCase().replace("jpeg", "jpg");
    return "jpg";
  }}

  function delay(ms) {{
    return new Promise(r => setTimeout(r, ms));
  }}

  // Fetch-based download: returns Blob or null
  async function fetchBlob(url) {{
    let resp;
    try {{
      resp = await fetch(url, {{ credentials: "include" }});
    }} catch (e) {{
      return null; // network error
    }}
    if (!resp.ok) return null;
    const ct = resp.headers.get("content-type") || "";
    if (!ct.startsWith("image/")) {{
      // Probably a CF challenge page (text/html)
      return null;
    }}
    const buf = await resp.arrayBuffer();
    if (buf.byteLength < 1024) {{
      // Too small — likely a challenge or error response
      return null;
    }}
    return new Blob([buf], {{ type: ct }});
  }}

  // Canvas-based fallback: returns Blob or null
  function canvasBlob(url) {{
    return new Promise(resolve => {{
      const img = new Image();
      img.crossOrigin = "anonymous";
      img.onload = () => {{
        const c = document.createElement("canvas");
        c.width  = img.naturalWidth  || img.width;
        c.height = img.naturalHeight || img.height;
        const ctx = c.getContext("2d");
        ctx.drawImage(img, 0, 0);
        c.toBlob(blob => resolve(blob || null), "image/png");
      }};
      img.onerror = () => resolve(null);
      img.src = url;
    }});
  }}

  // ── TRIGGER DOWNLOAD ────────────────────────────────────────────────────────
  function triggerDownload(blob, filename) {{
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {{
      URL.revokeObjectURL(a.href);
      document.body.removeChild(a);
    }}, 5000);
  }}

  // ── MAIN ─────────────────────────────────────────────────────────────────────
  await loadJSZip();
  console.log("[lex] JSZip loaded. Starting download of", URL_LIST.length, "images.");

  let zip      = new JSZip();
  let ok       = 0;
  let fail     = 0;
  let total    = URL_LIST.length;
  const CHECKPOINT_EVERY = 100;
  const LOG_EVERY        = 25;

  for (let i = 0; i < total; i++) {{
    const [factionSlug, slug, url] = URL_LIST[i];
    const ext      = extFromUrl(url);
    const zipPath  = factionSlug + "/" + slug + "." + ext;

    let blob = await fetchBlob(url);

    if (!blob) {{
      // Fallback: canvas
      blob = await canvasBlob(url);
    }}

    if (blob && blob.size > 1024) {{
      zip.file(zipPath, blob);
      ok++;
    }} else {{
      console.warn("[lex] FAIL", factionSlug + "/" + slug, url);
      fail++;
    }}

    // Progress log
    if ((i + 1) % LOG_EVERY === 0 || i === total - 1) {{
      console.log(`[lex] ${{i + 1}}/${{total}} | ok=${{ok}} fail=${{fail}}`);
    }}

    // Checkpoint zip every 100
    if ((i + 1) % CHECKPOINT_EVERY === 0) {{
      const checkName = `lex_images_checkpoint_${{String(i + 1).padStart(4, "0")}}.zip`;
      console.log(`[lex] CHECKPOINT -> ${{checkName}}`);
      const cpBlob = await zip.generateAsync({{ type: "blob" }});
      triggerDownload(cpBlob, checkName);
    }}

    await delay(250);
  }}

  // ── FINAL ZIP ────────────────────────────────────────────────────────────────
  console.log(`[lex] Generating final zip... ok=${{ok}} fail=${{fail}}`);
  const finalBlob = await zip.generateAsync({{ type: "blob" }});
  triggerDownload(finalBlob, "lex_images.zip");
  console.log(`[lex] DONE. lex_images.zip triggered. ok=${{ok}} fail=${{fail}}`);
}})();
"""

with open(OUT_JS, "w", encoding="utf-8") as f:
    f.write(js)

size_kb = os.path.getsize(OUT_JS) / 1024
print(f"[gen_phase2] Written: {OUT_JS}")
print(f"[gen_phase2] File size: {size_kb:.1f} KB")
